#server:
#  port: 9090
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  datasource:
#    url: jdbc:mysql://10.5.4.40:3306/test?characterEncoding=UTF-8
#    username: test
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect